/**
 * Verbatim disclaimer constants — non-editable, non-omittable.
 * Every report tier has its own disclaimer block rendered at the end of every report.
 */

const STANDARD = `STANDARD PROPERTY SNAPSHOT — SCOPE AND LIMITATIONS

This report was generated by automated query of publicly available county appraisal,
tax assessment, and parcel data sources. It reflects data displayed by those sources
at the time of query.

THIS REPORT IS NOT:
• A legal title opinion or title insurance commitment
• A guarantee of ownership, lien-free status, or encumbrance clearance
• A substitute for review by a licensed title company or real estate attorney
• A legally binding determination of any property right

Data accuracy depends on the public sources queried. TraceWorks makes no representations
regarding completeness or current accuracy of third-party public records. "Not Found"
and "Source Unavailable" labels reflect actual retrieval limitations — not omission.

For legal or transactional use, consult a licensed title company or attorney.`;

const OWNERSHIP_ENCUMBRANCE = `OWNERSHIP & ENCUMBRANCE INTELLIGENCE REPORT — SCOPE AND LIMITATIONS

This report reflects automated research of publicly available deed indexes,
grantor-grantee records, county clerk/recorder instruments, mortgage filings,
and related public filing indexes. It is an investigative research document.

THIS REPORT IS NOT:
• A title opinion, title commitment, or title insurance policy
• A guarantee of marketable or insurable title
• A complete or certified lien search
• A legal determination of ownership or encumbrance status
• A substitute for a licensed title company abstract or attorney opinion

This report can only show what is visible in publicly accessible filing indexes.
It NEVER asserts lien-free or unencumbered status. Gaps, breaks, and unavailable index periods are
explicitly noted and are not resolved by inference.

No section of this report should be used for legal or transactional decisions
without independent verification by a licensed title professional.`;

const PROBATE_HEIRSHIP = `PROBATE & HEIRSHIP INVESTIGATION REPORT — SCOPE AND LIMITATIONS

This report presents probabilistic research findings regarding possible heirs,
relatives, and associated contacts from publicly available data sources.
All findings are investigative leads only.

THIS REPORT IS NOT:
• A legal determination of heirship
• A probate court adjudication or legal heir certification
• A guarantee of family relationship accuracy
• A skip-trace guarantee or current-contact certification
• Legal advice of any kind

Every person identified carries an explicit confidence label (Confirmed / Likely /
Possible). These labels reflect evidentiary support only — they do not establish
legal identity, familial relationship, or heir status.

Contact information may be outdated. Manual verification is required before any
outreach or legal use of this information.

Heirship can only be legally established through probate proceedings or an
attorney-prepared heirship affidavit. This report does not substitute for either.`;

const ASSET_NETWORK = `ASSET & PROPERTY NETWORK REPORT — SCOPE AND LIMITATIONS

This report reflects automated research of publicly available county appraisal records,
parcel databases, and corporate/entity registration records to identify properties and
entities associated with a named owner or entity.

THIS REPORT IS NOT:
• A complete asset inventory or certified asset search
• A guarantee that all properties owned by this party are identified
• A legal determination of ownership or beneficial interest
• A substitute for judgment lien or UCC search by a title professional
• Legal advice of any kind

Results are limited to sources queried and jurisdictions searched. Properties held through
trusts, undisclosed nominees, or in non-searched jurisdictions will not appear.

This report is an investigative starting point, not a definitive asset record.`;

const COMPREHENSIVE = `COMPREHENSIVE INVESTIGATIVE REPORT — SCOPE AND LIMITATIONS

This report combines automated property, encumbrance, probate, heir-location, and
asset-network research into a single investigative document. It represents the maximum
output achievable from configured automated sources and is subject to the limitations
of each component workflow.

THIS REPORT IS NOT:
• A legal title opinion, title commitment, or title insurance policy
• A certified or complete chain-of-title abstract
• A legal determination of heirship or estate standing
• A guarantee of any property right, lien-free status, or asset completeness
• A substitute for a licensed title company, real estate attorney, or probate attorney
• Legal advice of any kind

Cross-source discrepancies are flagged but not resolved. Confidence labels reflect
evidentiary support only. "Manual Review Required" flags indicate areas where automation
cannot safely conclude and human professional review is required before legal or
transactional use.

Recommended next steps in this report are investigative workflow suggestions only
and do not constitute legal advice.`;

export const DISCLAIMERS = {
  standard:              STANDARD,
  ownership_encumbrance: OWNERSHIP_ENCUMBRANCE,
  probate_heirship:      PROBATE_HEIRSHIP,
  asset_network:         ASSET_NETWORK,
  comprehensive:         COMPREHENSIVE,
  custom:                STANDARD, // fallback for custom tier
};

export function getDisclaimer(tier, { timestamp, orderId }) {
  const text = DISCLAIMERS[tier] || DISCLAIMERS.standard;
  return text
    .replace('[TIMESTAMP]', timestamp || new Date().toISOString())
    .replace('[ORDER_ID]',  orderId   || 'N/A');
}
